### ISSUE TITLE
Crash on Startup (1.19.2-1.0.0-alpha.5)

### ISSUE THREAD

**Issue by LOLboy199** [Krxwallo/CheatModeFabric#4]
I'm following this mod's career with great interest, but it crashes on start no matter what I do. I typically run a lot of mods, but even with just minimal other mods, or no other mods running it still crashes the game on startup. I'm running a mod called 'not enough crashes' which provides some crash logs which may prove useful. I have no clue what is causing the crash or how to fix it, but here is the information provided by Not Enough Crashes and the Minecraft Log generated upon game startup:

Crashy Link: https://crashy.net/8JlojsvERfC1m90t4cqe

MInecraft Crash Report Link: https://bytebin.lucko.me/d8rzr3wJxJ

[2022-09-07-3.log.gz](https://github.com/Krxwallo/CheatModeFabric/files/9515223/2022-09-07-3.log.gz)

**Comment by Krxwallo** [comment]
This should be an issue caused by older versions. Is there a **folder** named "client.json" in your %appdata%\.minecraft\config folder? If there is, please delete it and start up the game again. Then it should work.

**Comment by LOLboy199** [comment]
That did the trick! Worked on startup and in game with all mods installed. Can't seem to get flight to turn off, and reach doesn't work on the server. But my initial issue is resolved.

**Comment by Krxwallo** [comment]
> Can't seem to get flight to turn off, and reach doesn't work on the server
1. You should be able to toggle flight (with double space) while the "Flight" button is ON and you should fall when setting it to OFF.
2. Reach is currently buggy.
