### ISSUE TITLE
cant go back to survival

### ISSUE THREAD

**Issue by vak321** [Krxwallo/CheatModeFabric#5]
ive built some stuff now i cant go back to survival mode and im stuck in creative tried taking the mod out of the folder but nothing works

**Comment by Krxwallo** [comment]
Did you close the game while the creative inventory was open by any chance?

**Comment by vak321** [comment]
> Did you close the game while the creative inventory was open by any chance?

yeah because it wouldn't switch back to survival no matter what so i closed the game and took out the mod and its still stuck like it

**Comment by Krxwallo** [comment]
Try the mod file below and execute the command `/survivalfix` in your world:

https://github.com/Krxwallo/CheatModeFabric/releases/download/v1.2.1-beta-survivalfix/CheatMode-1.21-1.2.1-beta-survivalfix.jar

Additionally, I uploaded a new version to curseforge (v1.2.1-beta) where this problem should be fixed!

**Comment by vak321** [comment]
> Try the mod file below and execute the command `/survivalfix` in your world:
> 
> https://github.com/Krxwallo/CheatModeFabric/releases/download/v1.2.1-beta-survivalfix/CheatMode-1.21-1.2.1-beta-survivalfix.jar
> 
> Additionally, I will upload a new version to curseforge where this problem should be fixed!

thanks mate
