### ISSUE TITLE
creative mode?

### ISSUE THREAD

**Issue by vak321** [Krxwallo/CheatModeFabric#6]
can you add  feature where you can switch to creative gamemode instead of just inventory? i got stuck in it yesterday  and building in it kind of grew on me no falling when opening inventory & not needing to take out blocks one by one from inventory for litemacia thanks

**Comment by Krxwallo** [comment]
Lol can't you just switch to creative mode then?

**Comment by Krxwallo** [comment]
If you want to do it "without cheats enabled" I am sure there are some mods that can do that...

**Comment by vak321** [comment]
> If you want to do it "without cheats enabled" I am sure there are some mods that can do that...

yeah but i got stuck in it yesterday was wondering if it was possible to go back again...

**Comment by Krxwallo** [comment]
You want to go back to survival mode? Then have a look at https://github.com/Krxwallo/CheatModeFabric/issues/5

**Comment by vak321** [comment]
> You want to go back to survival mode? Then have a look at #5

no no back to creative... or just lmk how it gliched out that i was in creative so i can do it again

**Comment by Krxwallo** [comment]
Haha. I don't really know why you would want to do that, but for versions before 1.2.1-beta you can close your game while the creative inventory is open and then the next time you open the game you will be in creative mode.

**Comment by vak321** [comment]
> Haha. I don't really know why you would want to do that, but for versions before 1.2.1-beta you can close your game while the creative inventory is open and then the next time you open the game you will be in creative mode.

its cus its easier to build things with litemacia thanks
